CaseStudyV2/force-app/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>A custom object for the jobs DB table</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CaseStudyV2/force-app/main/default/objects/Job__c/fields/JobCompany__c.field-meta.xml
<CustomField>
    <fullName>JobCompany__c</fullName>
    <label>Job Company</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

CaseStudyV2/force-app/main/default/objects/Job__c/fields/JobSummary__c.field-meta.xml
<CustomField>
    <fullName>JobSummary__c</fullName>
    <description>Summary of the job</description>
    <inlineHelpText>Brief summary of the job</inlineHelpText>
    <label>Job Summary</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

CaseStudyV2/force-app/main/default/objects/Job__c/fields/JobUrlLong__c.field-meta.xml
<CustomField>
    <fullName>JobUrlLong__c</fullName>
    <description>Job url but as a text field because the url field only allows a max of 255 characters.</description>
    <inlineHelpText>Url of the job posting.</inlineHelpText>
    <label>Job Url</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

CaseStudyV2/force-app/main/default/classes/LWCExampleController.cls
public inherited sharing class LWCExampleController {

    @AuraEnabled(Cacheable = true)
    public static List<Job__c> getJobs(){
        return [SELECT Id, Name, JobUrlLong__c, JobCompany__c, LastModifiedDate, JobSummary__c FROM Job__c ORDER BY Name limit 10];
    }

    // @AuraEnabled(Cacheable = true)
    // public static List<Contact> getContacts(){
    //     return [SELECT Id, FirstName,LastName, Phone, Email FROM Contact ORDER BY Name limit 10];
    // }
    
    // @AuraEnabled
    // public static void deleteContacts(list<Id> lstConIds){
    //     try {
    //         list<Contact> lstConsToDelete = new list<Contact>();
    //         System.debug('lstConIds ====> '+lstConIds);
    //         for(Id idCon : lstConIds) {
    //             lstConsToDelete.add(new Contact(Id = idCon));
    //         }
    //         if(!lstConsToDelete.isEmpty()) {
    //             delete lstConsToDelete;
    //         }
    //     }
    //     catch(Exception ex) {
    //         throw new AuraHandledException(ex.getMessage());
    //     }
    // }
    
    @AuraEnabled
    public static void deleteJobs(list<Id> lstJobIds){
        try {
            list<Job__c> lstJobsToDelete = new list<Job__c>();
            System.debug('lstJobIds ====> '+lstJobIds);
            for(Id idCon : lstJobIds) {
                lstJobsToDelete.add(new Job__c(Id = idCon));
            }
            if(!lstJobsToDelete.isEmpty()) {
                delete lstJobsToDelete;
            }
        }
        catch(Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }
}