CaseStudyV2/force-app/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>A custom object for the jobs DB table</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CaseStudyV2/force-app/main/default/objects/Job__c/fields/JobUrlLong__c.field-meta.xml
<CustomField>
    <fullName>JobUrlLong__c</fullName>
    <description>Job url but as a text field because the url field only allows a max of 255 characters.</description>
    <inlineHelpText>Url of the job posting.</inlineHelpText>
    <label>Job Url</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

CaseStudyV2/force-app/main/default/objects/JobApplication__c/JobApplication__c.object-meta.xml
<CustomObject>
    <description>Database for jobs that are applied or bookmarked. Will contain this for ALL users.</description>
    <label>JobApplication</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>JobApplication Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>JobApplications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CaseStudyV2/force-app/main/default/objects/JobApplication__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Defines the status of the selected job posting. Is it bookmarked or applied?</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Bookmarked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CaseStudyV2/force-app/main/default/classes/WebApiCallerDummy.cls
//This class is used for testing api calls and db injections, and can be deleted when things work. 
public with sharing class WebApiCallerDummy {
    public WebApiCallerDummy() {

    }

    @AuraEnabled
    public static String injectDummyJob(){
        // Add Job namd and url
        String successMessage = 'JOB WAS INSERTED!';
        Job__c jobRow = new Job__c(
            Name='HELLOOO SFDC Computing1 JOB TITLE DUMMY JOB ',
            JobUrlLong__c='https://www.google.com/');
        insert jobRow;
        System.debug(successMessage);
        System.debug(jobRow.ID);

        return successMessage;
    }

    @AuraEnabled
    public static String injectDummyJobApplication(){
        // Add account and related contact
        String successMessage = 'JOB APPLICATION WAS INSERTED!';
        JobApplication__c row = new JobApplication__c(
            Status__c='Applied' //Applied or Bookmarked
            );
        insert row;
        System.debug(successMessage);
        System.debug(row.ID);

        return successMessage;
    }


    public void callApiAnimals() {
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setEndpoint(
            'https://th-apex-http-callout.herokuapp.com/animals'
        );
        request.setMethod('GET');
        HttpResponse response = http.send(request);
        // If the request is successful, parse the JSON response.
        if (response.getStatusCode() == 200) {
            // Deserialize the JSON string into collections of primitive data types.
            Map<String, Object> results = (Map<String, Object>) JSON.deserializeUntyped(
                response.getBody()
            );
            System.debug(response.getBody());
            System.debug(results);
            // Cast the values in the 'animals' key as a list
            List<Object> animals = (List<Object>) results.get('animals');
            System.debug('Received the following animals:');
            for (Object animal : animals) {
                System.debug(animal);
            }
        }
    }

}