CaseStudyV2/force-app/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>A custom object for the jobs DB table</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CaseStudyV2/force-app/main/default/objects/Job__c/fields/JobCompany__c.field-meta.xml
<CustomField>
    <fullName>JobCompany__c</fullName>
    <label>Job Company</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

CaseStudyV2/force-app/main/default/objects/Job__c/fields/JobSummary__c.field-meta.xml
<CustomField>
    <fullName>JobSummary__c</fullName>
    <description>Summary of the job</description>
    <inlineHelpText>Brief summary of the job</inlineHelpText>
    <label>Job Summary</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

CaseStudyV2/force-app/main/default/objects/Job__c/fields/JobUrlLong__c.field-meta.xml
<CustomField>
    <fullName>JobUrlLong__c</fullName>
    <description>Job url but as a text field because the url field only allows a max of 255 characters.</description>
    <inlineHelpText>Url of the job posting.</inlineHelpText>
    <label>Job Url</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

CaseStudyV2/force-app/main/default/objects/JobApplication__c/JobApplication__c.object-meta.xml
<CustomObject>
    <description>Database for jobs that are applied or bookmarked. Will contain this for ALL users.</description>
    <label>JobApplication</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>JobApplication Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>JobApplications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CaseStudyV2/force-app/main/default/objects/JobApplication__c/fields/JobReference__c.field-meta.xml
<CustomField>
    <fullName>JobReference__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to reference selected job from job database.</description>
    <label>Job Reference</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>JobApplications</relationshipLabel>
    <relationshipName>JobApplications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

CaseStudyV2/force-app/main/default/objects/JobApplication__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Defines the status of the selected job posting. Is it bookmarked or applied?</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Bookmarked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CaseStudyV2/force-app/main/default/classes/ApexJobActionController.cls
public with sharing class ApexJobActionController {
    public ApexJobActionController() {

    }

    //GET ALL JOBS FROM MASTER DATABASE TABLE 
    @AuraEnabled(Cacheable = true)
    public static List<Job__c> getAllJobsQuery(){
        return [SELECT Id, Name, JobUrlLong__c, JobCompany__c, LastModifiedDate, JobSummary__c FROM Job__c ORDER BY Name limit 10];
    }
    
    //DELETE JOBS 
    @AuraEnabled
    public static void deleteJobsFromList(list<Id> lstJobIds){
        try {
            list<Job__c> lstJobsToDelete = new list<Job__c>();
            System.debug('lstJobIds ====> '+lstJobIds);
            for(Id idCon : lstJobIds) {
                lstJobsToDelete.add(new Job__c(Id = idCon));
            }
            if(!lstJobsToDelete.isEmpty()) {
                delete lstJobsToDelete;
            }
        }
        catch(Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }


    //Inject jobs into database 
    @AuraEnabled
    public static void injectJobsFromListIntoLookupDb(list<Id> lstJobIds, String status){
        if (status.equals('Applied') || status.equals('Bookmarked')){
            try {
                list<JobApplication__c> lstJobsToInject = new list<JobApplication__c>();
                System.debug('lstJobIds to inject ====> '+lstJobIds);
                for(Id jobId : lstJobIds) {
                    lstJobsToInject.add(new JobApplication__c(JobReference__c = jobId, Status__c = status));
                }
                if(!lstJobsToInject.isEmpty()) {
                    insert lstJobsToInject;
                }
            }
            catch(Exception ex) {
                throw new AuraHandledException(ex.getMessage());
            }
        }
        else{
            CalloutException e = new CalloutException();
            e.setMessage('The injected status for a job application is invalid!');
            System.debug(e);
            throw e;
        }
    }



}